In [ ]:
#Social_Networks_Ads.csv

**Importing the libraries**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
sns.set()

**Importing the dataset**

In [3]:
df = pd.read_csv('Social_Network_Ads.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [16]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [21]:
df['Age'].unique()

array([19, 35, 26, 27, 32, 25, 20, 18, 29, 47, 45, 46, 48, 49, 31, 21, 28,
       33, 30, 23, 24, 22, 59, 34, 39, 38, 37, 42, 40, 36, 41, 58, 55, 52,
       60, 56, 53, 50, 51, 57, 44, 43, 54], dtype=int64)

In [23]:
print(sorted(df['Age'].unique()))

[18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]


**Splitting the dataset into the Training set and Test set**

In [4]:
from sklearn.model_selection import train_test_split 

In [7]:
x = df.iloc[ : ,  2:4]
x.head(3)

Age  EstimatedSalary
0   19            19000
1   35            20000
2   26            43000

In [8]:
y = df['Purchased']
y.head(3)

0    0
1    0
2    0
Name: Purchased, dtype: int64

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20)

In [11]:
x_train.shape

(320, 2)

**Feature Scaling**

In [12]:
from sklearn.preprocessing import MinMaxScaler

In [13]:
scaling = MinMaxScaler()

In [ ]:
scaling.fit_transform(x_test)

In [ ]:
scaling.fit_transform(x_test)

**Fitting K-NN to the Training set**

In [24]:
from sklearn.neighbors import KNeighborsClassifier

In [25]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

**Predicting the Test set results**

In [27]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

**Making the Confusion Matrix**

In [28]:
from sklearn.metrics import confusion_matrix

In [30]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[40,  7],
       [14, 19]], dtype=int64)